###############################################################################
#
# Makefile for VM translator, project 7
#
# Students:
# Daniel Kerbel, ID ***REMOVED***, daniel.kerbel@mail.huji.ac.il
#
###############################################################################

all:
	chmod a+x VMtranslator

test:
	python3 -m unittest
	chmod +x ./mytest.sh
	./mytest.sh
